// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llmpqpvfokedxvynlrnr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsbXBxcHZmb2tlZHh2eW5scm5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3ODAxNDMsImV4cCI6MjA1OTM1NjE0M30.gx-gvWk-itdyu2Qu3J8tbnpROxM9iMPBpJ3kziTD_Yo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);